name: JEEPERS CREEPER-XMD 
services:
  - name: JEEPERS CREEPERS-XMD-service
    type: web
    ports:
      - 5000
    routes:
      - path: "/"
    build:
      type: docker
      dockerfile: ./Dockerfile
    regions:
      - fra
      - sin
      
